server:
  port: 8087

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

spring:
  application:
    name: ticket

  main:
    allow-bean-definition-overriding: true
  datasource:
    password: password
    url: jdbc:postgresql://postgres:5432/ticket
    username: levantos
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      boot:
        allow_jdbc_metadata_access: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    openfeign:
      client:
        config:
          user:
            url: http://localhost:8080
          cinema:
            url: http://localhost:8081
          movie:
            url: http://localhost:8084
          seat:
            url: http://localhost:8082
          schedule:
            url: http://localhost:8085
  sql:
    init:
      mode: never
  flyway:
    enabled: true

    locations: classpath:db/migration/ticket

  rabbitmq:
    addresses: rabbitmq:5672

management:
  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://zipkin:9411/
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    enabled: true
  instance:
    prefer-ip-address: true




#logging:
#  level:
#    org:
#      springframework: DEBUG


