services:
  postgres:
    container_name: postgres
    image:  postgres:16
    environment:
      POSTGRES_USER: levantos
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin:3.4.2
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - spring
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9411/" ]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s

  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - spring

  eureka-server:
    image: levantosina/eureka-server:latest
    container_name: eureka-server
    ports:
      -  "8761:8761"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
      - "MANAGEMENT.ZIPKIN.TRACING.ENDPOINT=http://zipkin:9411/"
    networks:
      - spring
    depends_on:
      - zipkin

  api-gateway:
    image: levantosina/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8083:8083"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
      - "MANAGEMENT.ZIPKIN.TRACING.ENDPOINT=http://zipkin:9411/"
    networks:
      - spring
    depends_on:
      - zipkin
      - eureka-server

  user:
<<<<<<< HEAD
    image: levantosina/user:latest
=======
    image: levantosina/user:27.11.2024.14.38.27
>>>>>>> 2cf2283a138f9c48e7fd270df0f64ee6285caa08
    container_name: user
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
      - "MANAGEMENT.ZIPKIN.TRACING.ENDPOINT=http://zipkin:9411/api/v2/spans"
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - postgres
      - rabbitmq

  movie:
    image: levantosina/movie:latest
    container_name: movie
    ports:
      - "8084:8084"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
      - "MANAGEMENT.ZIPKIN.TRACING.ENDPOINT=http://zipkin:9411/api/v2/spans"
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - postgres
      - rabbitmq

  cinema:
    image: levantosina/cinema:latest
    container_name: cinema
    ports:
      - "8081:8081"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
      - "MANAGEMENT.ZIPKIN.TRACING.ENDPOINT=http://zipkin:9411/api/v2/spans"
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - postgres
      - rabbitmq

  seat:
    image: levantosina/seat:latest
    container_name: seat
    ports:
      - "8082:8082"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
      - "MANAGEMENT.ZIPKIN.TRACING.ENDPOINT=http://zipkin:9411/"
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - postgres
      - rabbitmq
      - cinema

  schedule:
    image: levantosina/schedule:latest
    container_name: schedule
    ports:
      - "8085:8085"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
      - "MANAGEMENT.ZIPKIN.TRACING.ENDPOINT=http://zipkin:9411/api/v2/spans"
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - postgres
      - rabbitmq
      - seat
      - movie
      - cinema

  notification:
    image: levantosina/notification:latest
    container_name: notification
    ports:
      - "8086:8086"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
      - "MANAGEMENT.ZIPKIN.TRACING.ENDPOINT=http://zipkin:9411/api/v2/spans"
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - postgres
      - rabbitmq


networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres:
  pgadmin:
