server:
  port: 8083

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://USER
          predicates:
            - Path=/api/v1/users/**
        - id: cinema
          uri: lb://CINEMA
          predicates:
            - Path=/api/v1/cinemas/**

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/v2
    fetch-registry: true
    register-with-eureka: true

  instance:
    prefer-ip-address: true

