server:
  port: 8081

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

spring:
  application:
    name: cinema
  main:
    allow-bean-definition-overriding: true
  datasource:
    password: password
    url: jdbc:postgresql://postgres:5432/cinemas
    username: levantos
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      boot:
        allow_jdbc_metadata_access: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: never

  flyway:
    enabled: true
    baseline-on-migrate: false
    locations: classpath:db/migration/cinema

  rabbitmq:
    addresses: rabbitmq:5672

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    enabled: true
  instance:
    prefer-ip-address: true




