server:
  port: 8086

spring:
  application:
    name: notification
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/notification
    username: levantos
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      boot:
        allow_jdbc_metadata_access: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: never

  flyway:
    locations: classpath:db/migration/notification
    enabled: true

  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/v2
    fetch-registry: true
    register-with-eureka: true
    enabled: false
  instance:
    prefer-ip-address: true

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key

logging:
  level:
    org.springframework.amqp: DEBUG
    com.movie.notification.rabbitmq: DEBUG