server:
  port: 8082

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

spring:
  application:
    name: seat

  main:
    allow-bean-definition-overriding: true
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/seats
    username: levantos
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      boot:
        allow_jdbc_metadata_access: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: never
  flyway:
    enabled: true

    locations: classpath:db/migration/seat

  rabbitmq:
    addresses: localhost:5672

  cloud:
    openfeign:
      client:
        config:
          cinema:
            url: http://localhost:8081


management:
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    enabled: true
  instance:
    prefer-ip-address: true




#logging:
#  level:
#    org:
#      springframework: DEBUG


