server:
  port: 8082

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

spring:
  application:
    name: seat

  main:
    allow-bean-definition-overriding: true
  datasource:
    password: password
    url: jdbc:postgresql://postgres:5432/seats
    username: levantos
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      boot:
        allow_jdbc_metadata_access: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: never
  flyway:
    enabled: true

    locations: classpath:db/migration/seat

  rabbitmq:
    addresses: rabbitmq:5672

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/v2
    fetch-registry: true
    register-with-eureka: true
    enabled: true
  instance:
    prefer-ip-address: true




#logging:
#  level:
#    org:
#      springframework: DEBUG


