name: CI - Build and Deploy Eureka Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - eureka-server/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '21'



      - name: Build with Maven
        run: mvn clean install -DskipTests=true

      - name: Run tests
        run: mvn test

      - name: Build Docker image (Optional if using Jib)
        run: mvn clean install jib:build -DskipTests=true