name: CI - Build, Test, and Jib

on:
  pull_request:
    branches:
      - "main"
    paths:
      - eureka-server/**

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./eureka-server

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Compile the project
        run: mvn clean compile

      - name: Compile, Test, and Verify
        run: mvn verify -ntp -B
