name: CI - Build and Test

on:
  pull_request:
    branches:
      - "main"
    paths:
      - api-gateway/**
jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./api-gateway
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Build and run Integration Tests with Maven
        run: mvn -ntp -B verify