name: CI - Build Backend

on:
  pull_request:
    branches:
      - "main"
    paths:
      - user/**

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: levantos
          POSTGRES_PASSWORD: password
          POSTGRES_DB: users

        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      eureka-server:
          image: levantosina/eureka-server:latest
          ports:
            - 8761:8761
          options: >-
            --rm
            --health-cmd "curl -f http://localhost:8761/ || exit 1"
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

      zipkin:
        image: openzipkin/zipkin:latest
        ports:
          - 9411:9411
        options: >-
          --rm
          --health-cmd "curl -f http://localhost:9411/ || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'


      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD}}

      - name: Wait for Eureka
        run: |
            until curl -s http://localhost:8761; do
              echo "Waiting for Eureka server to be ready..."
              sleep 5
            done

      - name: Wait for Zipkin
        run: |
          until curl -s http://localhost:9411; do
            echo "Waiting for Zipkin server to be ready..."
            sleep 5
          done

      - name: Build and install all modules
        run: mvn -B install

      - name: Verify user module
        run: mvn -B verify -pl user
