name: CI - Build and Test

on:
  pull_request:
    branches:
      - "main"
    paths:
      - user/**
jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./user

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: levantos
          POSTGRES_PASSWORD: password
          POSTGRES_DB: users
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Build and run Integration Tests with Maven
        run: mvn -ntp -B verify