name: CI - Build Backend

on:
  pull_request:
    branches:
      - "main"
    paths:
      - user/**

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: levantos
          POSTGRES_PASSWORD: password
          POSTGRES_DB: users

        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Build and install all modules
        run: mvn -B install

      - name: Verify user module
        run: mvn -B verify -pl user
